from __future__ import annotations

import re
from pathlib import Path

from backend.app.core.skill_curator.models import SkillDraftRequest, SkillDraftResult

DEFAULT_DRAFT_ROOT = Path(".xagent") / "skill-curator" / "drafts"


def _slug(value: str) -> str:
    slug = re.sub(r"[^a-zA-Z0-9._-]+", "-", value.strip()).strip("-").lower()
    return slug or "skill-draft"


def render_skill_markdown(request: SkillDraftRequest) -> str:
    steps = request.steps or ["Review the task context.", "Apply the documented workflow.", "Verify the result."]
    step_text = "\n".join(f"{index + 1}. {step}" for index, step in enumerate(steps))
    evidence_count = len(request.evidence)
    return (
        f"---\n"
        f"name: {request.skill_name}\n"
        f"description: {request.description or 'Draft skill generated by X-Agent Skill Curator.'}\n"
        f"---\n\n"
        f"# {request.skill_name}\n\n"
        f"## Trigger\n\n{request.trigger or 'Use when this workflow is requested.'}\n\n"
        f"## Steps\n\n{step_text}\n\n"
        f"## Evidence\n\n- Curated from {evidence_count} evidence record(s).\n\n"
        f"## Safety\n\n"
        f"This draft is staged only. Review before installing or activating it.\n"
    )


def draft_skill(
    request: SkillDraftRequest,
    *,
    draft_root: Path = DEFAULT_DRAFT_ROOT,
) -> SkillDraftResult:
    content = render_skill_markdown(request)
    path = draft_root / _slug(request.skill_name) / "SKILL.md"
    if request.dry_run:
        return SkillDraftResult(
            skill_name=request.skill_name,
            status="planned",
            draft_path=str(path),
            content=content,
            activated=False,
        )

    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(content, encoding="utf-8")
    return SkillDraftResult(
        skill_name=request.skill_name,
        status="drafted",
        draft_path=str(path),
        content=content,
        activated=False,
    )
