"""feedback + feedback_analysis tables

Revision ID: 002_feedback_tables
Revises: 4e125ce868ca
Create Date: 2026-09-16

Why this revision is hand-written instead of autogenerated
----------------------------------------------------------
``backend/app/models/feedback.py`` used to declare its own
``Base = declarative_base()``.  ``backend/migrations/alembic/env.py`` sets
``target_metadata = Base.metadata`` where ``Base`` comes from
``backend.app.models`` — a *different* metadata object.  Both are real, so
``alembic revision --autogenerate`` could never see ``FeedbackModel`` /
``FeedbackAnalysisModel`` and these two tables silently never made it into any
revision.  ``alembic upgrade head`` therefore produced a Postgres schema
without ``feedback``, and the production ``FeedbackStorePostgres`` path could
not work at all.

That split is fixed in the same batch (``feedback.py`` now imports the
canonical ``Base``, matching what ``subscription.py`` already did), so future
changes to these tables *will* show up under ``--autogenerate``.  This
revision is written out by hand byte-for-byte from the model definition so the
``--autogenerate`` diff after applying it is empty.

Column parity notes
-------------------
* No ``server_default`` anywhere: the model uses Python-side ``default=`` /
  ``onupdate=`` only.  Adding a DB-side default here would make
  ``--autogenerate`` report permanent drift.
* ``extra_metadata`` is mapped to the physical column name ``metadata``.
* ``index=True`` on a mapped column produces ``ix_<table>_<column>``; those
  are created explicitly below because ``op.create_table`` does not derive them.
"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "002_feedback_tables"
down_revision: str | None = "4e125ce868ca"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    op.create_table(
        "feedback",
        sa.Column("id", sa.String(36), primary_key=True),
        sa.Column("user_id", sa.String(255), nullable=False),
        sa.Column("tenant_id", sa.String(255), nullable=False),
        sa.Column("feedback_type", sa.String(50), nullable=False),
        sa.Column("title", sa.String(500), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("severity", sa.String(50), nullable=False),
        sa.Column("status", sa.String(50), nullable=False),
        sa.Column("sentiment", sa.String(50), nullable=True),
        sa.Column("sentiment_score", sa.Float(), nullable=True),
        sa.Column("priority_score", sa.Float(), nullable=True),
        sa.Column("category", sa.String(255), nullable=True),
        sa.Column("tags", sa.JSON(), nullable=True),
        sa.Column("metadata", sa.JSON(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("resolved_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("resolution_note", sa.Text(), nullable=True),
    )
    op.create_index("ix_feedback_user_id", "feedback", ["user_id"])
    op.create_index("ix_feedback_tenant_id", "feedback", ["tenant_id"])
    op.create_index("ix_feedback_status", "feedback", ["status"])
    op.create_index("ix_feedback_created_at", "feedback", ["created_at"])
    op.create_index(
        "idx_feedback_user_tenant", "feedback", ["user_id", "tenant_id"]
    )
    op.create_index(
        "idx_feedback_status_created", "feedback", ["status", "created_at"]
    )
    op.create_index(
        "idx_feedback_severity_priority", "feedback", ["severity", "priority_score"]
    )

    op.create_table(
        "feedback_analysis",
        sa.Column("id", sa.String(36), primary_key=True),
        sa.Column("feedback_id", sa.String(36), nullable=False),
        sa.Column("sentiment_score", sa.Float(), nullable=False),
        sa.Column("sentiment_type", sa.String(50), nullable=False),
        sa.Column("category", sa.String(255), nullable=False),
        sa.Column("subcategory", sa.String(255), nullable=True),
        sa.Column("tags", sa.JSON(), nullable=False),
        sa.Column("priority_score", sa.Float(), nullable=False),
        sa.Column("urgency_score", sa.Float(), nullable=False),
        sa.Column("impact_score", sa.Float(), nullable=False),
        sa.Column("keywords", sa.JSON(), nullable=True),
        sa.Column("entities", sa.JSON(), nullable=True),
        sa.Column("analysis_metadata", sa.JSON(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
    )
    op.create_index(
        "ix_feedback_analysis_feedback_id", "feedback_analysis", ["feedback_id"]
    )
    op.create_index("idx_analysis_feedback", "feedback_analysis", ["feedback_id"])
    op.create_index("idx_analysis_category", "feedback_analysis", ["category"])


def downgrade() -> None:
    # Dropping a table takes its indexes with it on both Postgres and SQLite.
    op.drop_table("feedback_analysis")
    op.drop_table("feedback")
