import {
  mapActivityItem,
  mapAgentProfile,
  mapAuditEvent,
  mapAutomationRule,
  mapDataSource,
  mapKnowledgeSource,
  mapProjectItem,
  mapSettingsSection,
  mapTaskSummary,
  mapThreadItem,
  mapToolCapability,
  mapWorkbenchHome,
  mapWorkflowNode,
  mapWorkflowRun,
} from './adapters'
import type {
  ActivityItem,
  AgentProfile,
  AuditEvent,
  AutomationRule,
  DataSource,
  KnowledgeSource,
  PandaWorkbenchHome,
  ProjectItem,
  TaskSummary,
  ThreadItem,
  ToolCapability,
  WorkflowItem,
  WorkflowNode,
} from '../types'

export const adapterFixtureOutputs = {
  home: mapWorkbenchHome({
    brand: { product_name: 'Panda Agent', platform_name: '熊猫派达智能体应用管理平台' },
    metrics: { active_agents: 2, running_workflows: 3, pending_approvals: 1, api_calls: 99 },
    agent_activity: [{ id: 'act-api', title: '活动', tone: 'warning', owner_agent: '活动智能体', risk_level: 'warning', progress: 42, evidence_refs: ['ev-act-api'] }],
    workflow_runs: [{ id: 'wf-api', name: '流程', progress: 55, owner_agent: '编排智能体' }],
  }) satisfies PandaWorkbenchHome,
  activity: mapActivityItem({ id: 'act-api', title: '运行事件', status: 'running', tone: 'warning', owner_agent: '活动智能体', progress: 42, evidence_refs: ['ev-act-api'], updated_at: 'now' }) satisfies ActivityItem,
  workflow: mapWorkflowRun({ id: 'wf-api', name: 'API 工作流', owner_agent: '编排智能体', progress: 110, tone: 'success' }) satisfies WorkflowItem,
  task: mapTaskSummary({ id: 'task-api', title: 'API 任务', owner_agent: '任务智能体', progress: -10, risk_level: 'danger' }) satisfies TaskSummary,
  project: mapProjectItem({ id: 'project-api', name: 'API 项目', updated_at: 'today', owner_agent: '项目智能体', risk_level: 'success' }) satisfies ProjectItem,
  thread: mapThreadItem({ id: 'thread-api', title: 'API 线程', owner_agent: '线程智能体', progress: 52 }) satisfies ThreadItem,
  node: mapWorkflowNode({ id: 'node-api', title: 'API 节点', status: 'queued', x: 12, y: 34 }) satisfies WorkflowNode,
  agent: mapAgentProfile({ id: 'agent-api', name: 'API 智能体', permissions: ['repo:read'], load: 48 }) satisfies AgentProfile,
  knowledge: mapKnowledgeSource({ id: 'kb-api', name: 'API 知识源', documents: 12, last_sync: 'today' }) satisfies KnowledgeSource,
  data: mapDataSource({ id: 'data-api', name: 'API 数据源', records: 42, sync_state: 'realtime' }) satisfies DataSource,
  audit: mapAuditEvent({ id: 'audit-api', title: 'API 审计', risk_level: 'warning', evidence_refs: ['ev-1'] }) satisfies AuditEvent,
  tool: mapToolCapability({ id: 'tool-api', name: 'API 工具', invocations: 5 }) satisfies ToolCapability,
  automation: mapAutomationRule({ id: 'auto-api', name: 'API 自动化', last_run: 'today' }) satisfies AutomationRule,
  settings: mapSettingsSection({ id: 'settings-api', title: 'API 设置', description: 'tenant', status: 'ready' }),
}
