"""${message}

Revision ID: ${up_revision}
Revises: ${down_revision}
Create Date: ${create_date}

"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# Revision identifiers used by Alembic
revision: str = ${repr(up_revision)}
down_revision: Union[str, None] = ${repr(down_revision)}
branch_labels: Union[str, Sequence[str], None] = ${repr(branch_labels)}
depends_on: Union[str, Sequence[str], None] = ${repr(depends_on)}


def upgrade() -> None:
    """Upgrade database schema."""
    # ### commands auto generated by Alembic ###
    # Please edit the code above to reflect changes made to the database schema.
    pass


def downgrade() -> None:
    """Downgrade database schema."""
    # ### commands auto generated by Alembic ###
    # Please edit the code above to reflect changes made to the database schema.
    pass
